[package]
name = "colordle"
version = "0.1.0"
edition = "2026"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
rand = "0.10.0"
reqwest = { version = "0.13.2", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
